config/routes.rb
Rails.application.routes.draw do
 
 resources :appointments

  get 'appointments/:id/confirm' => "appointments#confirm", as: :confirm
  get 'appointments/:id/cancel' => "appointments#cancel", as: :cancel
  get 'appointmentshistory' => "appointments#history", as: :history

 root 'pages#home'

 get '/about' => 'pages#about'
 get '/services' => 'pages#services'
 get '/contact' => 'pages#contact'

 get 'signup'  => 'users#new' 
resources :users

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base 

  has_secure_password 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user 

	def current_user 
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end
	
	def require_user 
	  redirect_to '/login' unless current_user 
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :confirm, :cancel]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.where(status: 'new').order(:create_date)
    
  end

  # GET /appointmentshistory
  def history
    @appointments = Appointment.where.not(status: 'new').order(:create_date)
    @history = true
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # GET /appointments/1/submit
  def confirm
    @appointment.status = 'confirmed'
    
    respond_to do |format|
      if @appointment.save()
        format.html { redirect_to appointments_url, notice: 'appointment was successfully confirmed.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /appointments/1/cancel
  def cancel
    @appointment.status = 'cancelled'
    
    respond_to do |format|
      if @appointment.save()
        format.html { redirect_to appointments_url, notice: 'appointment was successfully cancelled' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.status = 'new'
    @appointment.create_date = Time.now
    respond_to do |format|
      if @appointment.save
       @notice = ('The appointment was succesfuly create, you will recieve an email about your appointment confirmation')
        format.html { render :success, notice: ('The appointment was succesfuly create, you will recieve an email about your appointment confirmation') }
        format.json { render :success, status: :ok, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'appointment was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :time, :client_name, :client_email, :client_phone, :service,
        )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def new 
end

def create
  @user = User.find_by_name(params[:session][:name])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to '/about'
  else
    redirect_to '/'
  end 
end
def destroy 
  session[:user_id] = nil 
  redirect_to '/' 
end







end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create 
  @user = User.new(user_params) 
  if @user.save 
    session[:user_id] = @user.id 
    redirect_to '/' 
  else 
    redirect_to '/signup' 
  end 
end




private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<style type="text/css">
   {
    width: 800px;
  }
  div.field {
    width: 400px;
    height: 50px;
  }
  div.field_container {
    float: left;
    width: 550px;
  }
</style>

<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading"><h2>Online Appointment Set Up</h2></div>
    <div class="panel-body">
  <div class="field_container left">
    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_field :date %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
       <%= f.time_select :time,  {ampm: true} %> 
      
    </div>
    <div class="field">
      <%= f.label :reason_for_Visit %><br>
      <%= f.text_field :service%>
    </div>
  
  </div>  
 
  <div class="field_container right">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :client_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :client_email %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :client_phone %>
       </div>
    </div>
   
    </div>
      </div>
   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/_list.html.erb
<div class="media">
  <div class="media-body">
    
    <table class="table table-hover">
  <thead>
    <tr>
      <th><%= t 'Date' %></th>
      <th><%= t 'Time' %></th>
      <th><%= t 'Reason' %></th>
      <th><%= t 'Patient Name' %></th>
      <th><%= t 'Patient Email' %></th>
      <th><%= t 'Patient Phone Number' %></th>
      <% if @history %>
        <th><%= t 'Status' %></th>
      <% end %>
      <th colspan="4"></th>
    </tr>
      
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.time.strftime("%I:%m %p") %></td>
        <td><%= appointment.service %></td>
        <td><%= appointment.client_name %></td>
        <td><%= appointment.client_email %></td>
        <td><%= appointment.client_phone %></td>
        <% if @history %>
          <td><%= t :"appointment.cancel.#{appointment.status}" %></td>
        <% end %>
        <td><%= link_to 'Show', appointment,class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment),class: 'btn btn-mini btn-success'  %></td>
         <td><%= link_to 'Remove', appointment, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

<br>

app/views/appointments/edit.html.erb
<h3><%= 'Edit Appointment' %></h3>

<%= render 'form' %>



<%= link_to 'Confirm', confirm_url(@appointment),class: 'btn btn-mini btn-primary' %>
<%= link_to 'Cancel', cancel_url(@appointment),class: 'btn btn-mini btn-danger' %>
<br />

<%= link_to 'Back', appointments_path,class: 'btn btn-mini btn-success' %>

app/views/appointments/history.html.erb
<h3><%= 'Appointment History' %></h3>
<p id="notice"><%= notice %></p>

<%= render 'list' %>

<%= link_to 'List of New Appointments', appointments_path, class:'btn btn-warning' %>


app/views/appointments/index.html.erb
<h3><%= t 'Appointments List' %></h3>
<p id="notice"><%= notice %></p>
<%= render 'list' %>

<%= link_to 'Processed Appointments', history_url,class:'btn btn-primary' %>

app/views/appointments/new.html.erb
<%= render 'form' %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong><%=  'Date' %>:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong><%=  'Time' %>:</strong>
  <%= @appointment.time.strftime("%I:%m %p") %>
</p>
<p>
  <strong><%=  'Service' %>:</strong>
  <%= @appointment.service %>
</p>

<p>
  <strong><%=  'Patient Name' %>:</strong>
  <%= @appointment.client_name %>
</p>

<p>
  <strong><%=  'Patient Email' %>:</strong>
  <%= @appointment.client_email %>
</p>

<p>
  <strong><%= 'Patient Phone' %>:</strong>
  <%= @appointment.client_phone %>
</p>




<%= link_to ('confirm'), confirm_url(@appointment),class: 'btn btn-mini btn-primary' %>
<%= link_to ('cancel'), cancel_url(@appointment),class: 'btn btn-mini btn-danger' %>
<br />
<%= if @appointment.status == 'new' then link_to ('edit'), edit_appointment_path(@appointment),class: 'btn btn-mini btn-success' end %>


app/views/appointments/success.html.erb
<p id="notice"><%= @notice %></p>


<p>
  <strong><%=  'Date' %>:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong><%=  'Time' %>:</strong>
  <%= @appointment.time.strftime("%I:%m %p") %>
</p>

<p>
  <strong><%=  'Name' %>:</strong>
  <%= @appointment.client_name %>
</p>

<p>
  <strong><%=  'Email' %>:</strong>
  <%= @appointment.client_email %>
</p>

<p>
  <strong><%=  'Phone' %>:</strong>
  <%= @appointment.client_phone %>
</p>

<p>
  <strong><%=  'Service' %>:</strong>
  <%= @appointment.service %>
</p>


app/views/layouts/_header.html.erb
<header class="clearfix">
  <%= link_to root_path, id: 'logo' do %>
    
    
  <% end %>
  <nav>
      <li>
        <%= link_to 'Home', root_path, class: yield(:page) == 'home' ? 'selected' : nil %>
      </li>
      <li>
        <%= link_to 'About', about_path, class: yield(:page) == 'about' ? 'selected' : nil %>
      </li>
      <li>
        
        
      </li>
      </li>
      <li>
        <%= link_to 'Online Appointment', new_appointment_path, class: yield(:page) == 'contact' ? 'selected' : nil %>
  </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <link href='http://fonts.googleapis.com/css?family=Changa+One|Open+Sans:400italic,700italic,400,700,800' rel='stylesheet' type='text/css'>  
  <%= stylesheet_link_tag    "application", media: 'all', "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/header' %>
  <div id="wrapper">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>

app/views/pages/home.html.erb
<div class="service_menu">
                <h2>Make an appointment</h2>
                <div class="ser_col1 ser_com">

                    <section id="primary">
                   <div class="items">     
                      
                        <p>To book an appointment, you can book online or contact the Health Services reception.</p>
                    </div>

                    <%= image_tag 'doctor.JPG',  class: 'pic-icon'%>

app/views/pages/services.html.erb
</script>

    	                           
            <div class="service_menu">
                <h2>Service Menu</h2>
                <div class="ser_col1 ser_com">

                    <section id="primary">
                   <div class="items">     
                        <span class="ser_title">Haircuts</span><span class="ser_cost"></span>
                        <p>A custom hair cut by one of our professional stylists.</p>
                    </div>
                  
                   <div class="items">     
                        <span class="ser_title">Short Hair Cut</span><span class="ser_cost">$50 & up</span>
                        
                    </div>
                  
                   <div class="items">     
                        <span class="ser_title">Men&#8217;s Hair Cut</span><span class="ser_cost">$30</span>
                      
                    </div>
                  
                   <div class="items">     
                        <span class="ser_title">Children&#8217;s Hair Cut</span><span class="ser_cost">$30</span>
                        
                    </div>
                  
                   <div class="items">     
                        <span class="ser_title">Color &#038; Highlights</span><span class="ser_cost">$130 & up</span>
                        
                    </div>
                  
                   <div class="items">     
                        <span class="ser_title">Partial Foil</span><span class="ser_cost">$185 & up</span>
                       
                    </div>
                  
                   <div class="items">     
                        <span class="ser_title">Toner</span><span class="ser_cost">$25</span>
						
						 <div class="items">     
                        <span class="ser_title">balayge</span><span class="ser_cost">$25</span>
                        
                    </div>
                 </section>                     
                                 

           
                
                                      
                  
                </div>
                <div class="clear"></div> 
            </div>
            
            <div class="clear"></div> 
        </div>


      

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :name, :placeholder => "First name" %>
          <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>